### ISSUE TITLE
Please implement async.js on loops

### ISSUE THREAD

**Issue by Metric** [fent/node-feedsub#15]
Hi there, nice library, but you really need to implement async.series and async.eachSeries(), instead of using for() and array.forEach().

This needs to be implemented on both NewsEmitter (this one especially, because of the comparison loop), and on FeedSub results.forEach().

Right now NewsEmitter and FeedSub are causing blocking because of their forEach and for loops. NewsEmitter is causing the worst of the blocking due to all the comparisons.

I already implemented this on my local copy of FeedSub / NewsEmitter. It now no longer blocks the node thread as it is comparing / emitting the items.

**Comment by fent** [comment]
On NewsEmitter, would not be able to compare asynchronously with its current API, since `.emit()` returns `true` or `false` depending on if it is a new item. You can also use the `maxHistory` option with it.

On FeedSub `results.forEach()`, it shouldn't take much CPU usage unless it's by the listener(s) for the `item` event.

**Comment by Metric** [comment]
Sure you can, just change the api and use a callback function for the true
or false. That is what I did in my local copy. You can either A: make the
news emitter.emit only accept an event, item, and callback. Or B: test the
last argument to see if it is a function to use for the callback. Really
though, the .emit function is just a comparer and really shouldn't accept
more than an event, item, and callback. It isn't like a regular event
emitter.

**Comment by fent** [comment]
Tried to think of another way to keep this synchronous, by keeping a map of events emitted, and not just a list to loop through.

Check out
https://github.com/fent/node-newsemitter/tree/identifier
https://github.com/fent/node-feedsub/tree/identifier

Let me know if this works for you

**Comment by Metric** [comment]
Looks good, but I noticed in feedsub in that version you forgot to set the manageHistory option to true. So, it might be trying to add history twice with the newsemitter doing auto, and then you adding history in via feedsub. Though, I still recommend using async.js instead of for loops when you can.

One other thing, I also noticed the items coming in from feedsub on the .on('item') and .on('items') are reversed from their actual order in the actual feed. It goes oldest to newest (bottom to top) instead, of newest to oldest (top to bottom). Probably should reverse the array before emitting the individual items and items array.

**Comment by fent** [comment]
`manageHistory` is now false, it adds the items manually on first read. But on subsequent, it's faster to let NewsEmitter handle it, since `NewsEmitter#addHistory()` would be doing the same thing, but without emitting any event.

The order of the items is reversed from the actual feed, because FeedSub assumes the feed will be ordered from newest to oldest. And it made sense to emit these items sorted by time, since the FeedSub object is treated like it runs chronologically.
